services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4444/status"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  tests:
    build: .
    environment:
      SELENIUM_REMOTE_URL: http://selenium:4444
    depends_on:
      selenium:
        condition: service_healthy
    volumes:
      - ./reports:/app/reports
      - ./allure-results:/app/allure-results